manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      # remote: petejohanson
      # revision: core/zephyr-3.5-update
      # revision: studio/raw-hid-exploration
      clone-depth: 1
      import: app/west.yml
  self:
    path: zmk_keyboards
